language: c

env:
  - XCFLAGS="-g -fsanitize=address" XLDFLAGS=-fsanitize=address ASAN_OPTIONS=detect_leaks=0

install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH=$PATH:~/.cargo/bin

script:
  - make
  - make test

compiler:
  - clang
  - gcc

matrix:
  fast_finish: true
  include:
    # TODO: test (instead of just build) on OS X
    # https://github.com/Ristretto/libristretto255/issues/19
    - os: osx
      compiler: clang
      env: []
      install: ""
      script: make
    - os: osx
      compiler: gcc
      env: []
      install: ""
      script: make

branches:
  only:
    - master
