language: c

install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH=$PATH:~/.cargo/bin

env:
  - XCFLAGS=-g

script:
  - make
  - make test

compiler:
  - gcc
  - clang

os:
  - osx
  - linux

matrix:
  fast_finish: true
  exclude:
    - os: linux
      compiler: clang
  include:
    - os: linux
      compiler: clang
      script:
        # Enable ASAN as a workaround for ristretto_gen_tables SEGV
        # See: https://github.com/Ristretto/libristretto255/issues/24
        - XCFLAGS="-g -fsanitize=address" XLDFLAGS=-fsanitize=address ASAN_OPTIONS=detect_leaks=0 make
        - make clean
        - make build/obj/bin/ristretto_gen_tables && rm build/obj/ristretto_gen_tables.o
        - clang -std=c99 -fno-strict-aliasing -g -Iinclude -Isrc -Isrc/arch/x86_64 -O2 -march=native -ffunction-sections -fdata-sections -fomit-frame-pointer -fPIC -c -o build/obj/ristretto_tables.o src/ristretto_tables.c
        - ar rcs build/lib/libristretto255.a build/obj/*.o
        - cd tests && cargo test --all --lib

branches:
  only:
    - master
