environment:
  LLVM_VERSION: 5.0.0
  RUST_BACKTRACE: 1
  matrix:
  - TARGET: gnu
  # TODO: test on MSVC
  # - TARGET: msvc

image: Visual Studio 2017

platform:
  # TODO: test on 32-bit architectures
  # - x86
  - x64

branches:
  only:
  - master

install:
  - if %PLATFORM% == x86 set ARCH=32&set RUST_PLATFORM=i686&set MINGW_BITS=32
  - if %PLATFORM% == x64 set RUST_PLATFORM=x86_64&set MINGW_BITS=64
  - if %PLATFORM% == x86 call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - if %PLATFORM% == x64 call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %RUST_PLATFORM%-pc-windows-%TARGET% --default-toolchain stable
  - set PATH=C:\msys64\usr\bin;%USERPROFILE%\.cargo\bin;%PATH%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if %TARGET%==gnu set PATH=C:\msys64\mingw%MINGW_BITS%\bin;C:\msys64\usr\bin\;%PATH%
  - if %TARGET%==gnu set "MINGW_URL=http://repo.msys2.org/mingw/%RUST_PLATFORM%/mingw-w64-%RUST_PLATFORM%"
  - if %TARGET%==gnu set "URL_VER=%LLVM_VERSION%-1-any.pkg.tar.xz"
  - if %TARGET%==gnu bash -lc "pacman -U --noconfirm $MINGW_URL-clang-$URL_VER $MINGW_URL-llvm-$URL_VER"
  - if %TARGET%==gnu bash -lc "clang --version"
  - if %TARGET%==msvc appveyor-retry appveyor DownloadFile http://releases.llvm.org/%LLVM_VERSION%/LLVM-%LLVM_VERSION%-win64.exe -FileName llvm-installer.exe
  - if %TARGET%==msvc 7z x llvm-installer.exe -oc:\llvm-binary
  - if %TARGET%==msvc set PATH=C:\llvm-binary\bin;%PATH%
  - if %TARGET%==msvc where clang
  - if %TARGET%==msvc clang --version

build_script:
  - if %TARGET%==gnu make
  - if %TARGET%==gnu make test
  - if %TARGET%==msvc call "ci\test.bat"

test: off
